# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=1000),
        ),
    ]
