

version: "3"
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ../database-backup:/database-backup
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    # environment:
    #   - cluster.name=docker-cluster
    #   - bootstrap.memory_lock=true
    #   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #   # - ES_HOST=http://localhost:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  webscraping:
    restart: always
    build: Scraping/.
    command: bash -c "python /var/www/propertyappraisal/Scraping/WebScraping.py" 
    volumes:
      - ../propertyappraisal/Scraping/:/var/www/propertyappraisal/Scraping/
    networks:
      - esnet
    depends_on: 
      - db
      - elasticsearch 
    environment: 
      - DB_HOST=db
      - ES_HOST=elasticsearch
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=True
      - ES_USE_SSL=False
      # - ES_HOST=elasticsearch  
  kibana:
    build:
      context: kibana/
      # args:
      #   ELK_VERSION: $ELK_VERSION
    volumes:
      -  ../propertyappraisal/:/var/www/
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch
  django:
    restart: always
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py makemigrations appraisal && python manage.py migrate && python manage.py migrate appraisal && python /var/www/propertyappraisal/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../propertyappraisal:/var/www/propertyappraisal
    ports:
     - "8000:8000"
    networks:
      - esnet
    depends_on:
     - db
     - elasticsearch
    environment: 
      - DB_HOST=db
      - ES_HOST=elasticsearch
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=True
      - ES_USE_SSL=False
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  postgres-config:
  postgres-data:
  postgres-logs:
networks:
  esnet:
