# @Author: Matthew Hale <mlhale>
# @Date:   2018-02-14T23:02:38-06:00
# @Email:  mlhale@unomaha.edu
# @Filename: docker-compose.yml
# @Last modified by:   matthale
# @Last modified time: 2018-09-06T15:16:18-05:00
# @License: Funset is a web-based BIOI tool for visualizing genetic pathway information. This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
# @Copyright: Copyright (C) 2017 Matthew L. Hale, Dario Ghersi, Ishwor Thapa



version: "3"
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ../database-backup:/database-backup
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
  #   container_name: elasticsearch4
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata1:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - esnet

  django:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py makemigrations appraisal && python manage.py migrate && python manage.py migrate appraisal && python /var/www/propertyappraisal/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../propertyappraisal:/var/www/propertyappraisal
    ports:
     - "81:8000"
    depends_on:
     - db
    #  - elasticsearch
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  postgres-config:
  postgres-data:
  postgres-logs:
networks:
  esnet:
