

version: "3"
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ../database-backup:/database-backup
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  django:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py makemigrations appraisal && python manage.py migrate && python manage.py migrate appraisal && python /var/www/propertyappraisal/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../propertyappraisal:/var/www/propertyappraisal
    ports:
     - "8000:8000"
    depends_on:
     - db
     - elasticsearch
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  postgres-config:
  postgres-data:
  postgres-logs:
networks:
  esnet:
